### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by JosePereiraUA** [jkwang93/Atom-Path-Descriptor-based-machine-learning#1]
Hi! 

Nice work, here.
Just have one question: would it be possible to have a trained model available?
And perhaps with a quick tutorial on how to use the trained model (what are the inputs, etc)?

Thank you!

**Comment by jkwang93** [comment]
Thank you very much for your support of our work. Because the model size is too large, it is not very convenient to upload. We have built a charge prediction website(deepchargepredictor) that contains a variety of charge prediction methods, which can directly submit your task in this web: http://cadd.zju.edu.cn/deepchargepredictor/.

**Comment by JosePereiraUA** [comment]
Thank you for your answer. I've since explored your website: good work!
I'm currently working on a new protein design package ([ProtoSyn.jl](https://github.com/sergio-santos-group/ProtoSyn.jl)) and would prefer a more direct and integrated approach. I understand if it is not possible or feasible to share a trained model. It would greatly help my work by being able to re-calculate charges given conformation changes on the go. I feel like there is some interesting science to be made by combining the two tools.

If you'd like to talk more, feel free to reach out. And thank you once again for the amazing work.

**Comment by jkwang93** [comment]
Thank you for your attention, your work is also very meaningful.  I am also preparing to start working on protein design and have followed you in researchgate, so we can keep in touch more later:)
